### PR TITLE
Adequate support for stream responses

### PR DESCRIPTION
**Pull request by Foxy-Loxy**
Added functionality of piping streamed responses without having to return callback with pipe in it

## Description
Created new content type of StreamContent and added proper handle for it in `server.ts` on return

## Related Issue
https://github.com/inversify/InversifyJS/issues/850

## Motivation and Context
Fixes the bug

## How Has This Been Tested?
Unit test were written.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by dcavanagh** [comment]
@Foxy-Loxy will you please update this PR and resolve the conflicts? Thank you

**Comment by Foxy-Loxy** [comment]
@dcavanagh , sorry for long delay in answer. I though that project is no longer maintained so never checked on PR. I did conflict resolvment and adapted new linter styles. Feel free to add any more inputs.

**Comment by Foxy-Loxy** [comment]
@dcavanagh, I'm not sure if it's still relevant, but I've updated code to resolve all conflicts. Would be really cool if you, or anyone from maintainers would have time to check this out :)

**Review by PodaruDragos — APPROVED** [review]
LGTM, thanks.

**Comment by PodaruDragos** [comment]
@dcavanagh after we merge this, can we also release with w/e is on master ?
It's been a very long time since we haven't released.

**Comment by Foxy-Loxy** [comment]
Hi @dcavanagh @PodaruDragos ! Any chance that this PR goes anywhere?

**Comment by bhupesh-sf** [comment]
when will this be published on npm?

**Comment by Jameskmonger** [comment]
@bhupesh-sf I have added this to the `6.0.3` milestone, it will be published in the next release. We had some issues with the last publish that need to be resolved first.

**Comment by Jameskmonger** [comment]
@bhupesh-sf I have added this to `6.5.0` milestone and it will be published in the next release, I will aim to make a release this week. Thank you and apologies for the delay.

**Comment by noahg** [comment]
@Jameskmonger any update on the `6.5.0` release to npm? Thanks!

**Pull request merged**
