### PR TITLE
initial code migration

### PR DESCRIPTION
**Pull request by codyjs**

### CODE REVIEW

**Comment by remojansen** [comment]
Great work :+1: sorry I have not been able to help you with this so far :cry: I will try to set up a build on Travis CI as soon as I can. Will keep you updated.

**Comment by codyjs** [comment]
Thanks, and no worries! I may make a few more PRs in the coming days as I learn more about publishing npm packages.

**Comment by remojansen** [comment]
No problem, feel free to ask fro help. We had some problems in the past and we have learned how to solve them I recommend you to take a look to [one of our gulpfile.js](https://github.com/inversify/InversifyJS/blob/master/gulpfile.js) files. 

You can see that we build the application a few times and store the output in folders: 

- `dist` (for browsers) 
- `es` for people working with webpack and babel
- `lib` for people working with browserify. 

All this folders are included in the npm package. 

Another thing to mention is that we distribute our type definitions in a second package: https://github.com/inversify/dts

**Comment by codyjs** [comment]
Thanks a lot for the info. Working on type definitions now, expect a PR soon :wink:

**Pull request merged**
