### PR TITLE
Integration with Inversify standards + Unit tests

### PR DESCRIPTION
**Pull request by codyjs**
I fixed all code to conform to the tslint rules, and added the Inversify gulpfile.

Also did some refactoring and added some unit tests.

### CODE REVIEW

**Comment by remojansen** [comment]
Thanks a lot for this PR :) I was going to ask you to merge the Travis config but I see that you have already done it :) I will see if the build pass and merge it.

**Comment by remojansen** [comment]
I'm running it again there was a problem with the codecov auth... it is looking good :+1:

**Comment by remojansen** [comment]
Merged into master :tada: thanks a lot for contributing :smile:

**Comment by codyjs** [comment]
Great! Thanks a lot for the help

**Pull request merged**
