### PR TITLE
Non-native promise handling

### PR DESCRIPTION
**Pull request by RohaanAdvani68**
## Description
The changes made enable non-native promise handling functionality for inversify-express-utils, such that both native es6 promises as well as promise libraries such as Bluebird are supported.

## Related Issue
https://github.com/inversify/InversifyJS/issues/624

## Motivation and Context
Inversify-express-utils should give programmers the flexibility to use a promise library of their choice.

## How Has This Been Tested?
All unit tests pass.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by lholznagel** [comment]
Could you add bluebird as a dev dependency and write a small and simple unit test?

Not that this is necessary, but its a nice to have :)

**Comment by mikeroth7** [comment]
@lholznagel any idea when there will be a new release containing this PR?

**Comment by lholznagel** [comment]
Currently I don´t have the permission to create a new relase. @remojansen is looking into it. Will do it as soon as I can :)

**Comment by remojansen** [comment]
I just release inversify-express-utils@4.0.1 sorry for the delay and thanks for the help 👍

**Pull request merged**
