### PR TITLE
Provide the way to inject middleware to controller/methods

### PR DESCRIPTION
**Pull request by maxmalov**
## Related Issue

https://github.com/inversify/InversifyJS/issues/487

## Motivation and Context

See description in the https://github.com/inversify/InversifyJS/issues/487

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by remojansen** [comment]
Hi @maxmalov thanks a lot for this PR. Great work :+1:

**Comment by mikeroth7** [comment]
Was this feature removed in 4.0.0?

I'm wanting to create a custom decorator, like @authorize() for example, to add passport  middleware. Is there a simple way to do this? From what I can tell, I will have to push the middleware function onto the middleware array in the _controller-method metadata. It seems like that might be a bit hacky, so if there's a better way to achieve this I'd appreciate any info.

**Comment by remojansen** [comment]
@mikeroth7 You can pass a symbol and the middleware is then injected: https://github.com/inversify/inversify-express-utils/blob/4e8f64ac891606dd48ec1aac579e43ca37f4c274/test/framework.test.ts#L506

**Comment by mikeroth7** [comment]
Thanks @remojansen. If I preferred a custom decorator, is there anything wrong with my approach of mutating the metadata for that route?

**Comment by remojansen** [comment]
@mikeroth7 if you mutate the meta data, future releases could break your project because the metadata format is not a public API. I have seen projects that wrap our decorators with custom decorators [example](https://github.com/GuidionDev/inversify-express-doc/blob/master/src/inversify-express-docs.ts) to generate additional metadata.

**Comment by mitjarogl** [comment]
@maxmalov Hey, great work. Is it possible to add this same feature into inversify-restify-utils? Thanks.

**Pull request merged**
