### PR TITLE
fix: remove 204 return falsey & add default expressjs behavior on emp…

### PR DESCRIPTION
**Pull request by rsaz**
…ty-void return

## Description

Described here: https://github.com/inversify/inversify-express-utils/issues/255#issuecomment-2230392628
Test modified to validate timeout rather than 204

## Motivation and Context

Not able to return error, middleware, next. Issue on `ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`

## How Has This Been Tested?

```ts
it("should work for controller methods who's return value is falsey", (done) => {
            @controller("/user")
            class TestController {
                @httpDelete("/") public async delete(): Promise<void> {
                    //
                }
            }

            server = new InversifyExpressServer(container);
            void supertest(server.build())
                .delete("/user")
                .timeout({ response: 1000, deadline: 2000 })
                .end((err, res) => {
                    if (err) {
                        if (err.timeout) {
                            // The request timed out as expected because no response was sent
                            done();
                        } else {
                            // Some other error occurred
                            done(err);
                        }
                    } else {
                        // If we get here, the request did not hang, and a response was received
                        done(new Error("Expected request to hang, but a response was received"));
                    }
                });
        });
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by notaphplover — COMMENTED** [review]
Looks great!

Can you update the changelog with a new entry in the unreleased section?

**Comment by rsaz** [comment]
> Looks great!
> 
> Can you update the changelog with a new entry in the unreleased section?

Done!

**Comment by CGReinhold** [comment]
Hi!

Am I correct to understand that with this change we are now required to always use a `res.sendStatus(XXX)` in case we don't have a "truthy" return payload?

This seems to me a breaking change, as before we wouldn't need to send the status in those cases, so bumping the version ended up breaking endpoints that had no response and relied on the default 204 response.

I fully understand if that is indeed the expected behavior, since the README also shows this pattern, but to me it seems a bit odd having to configure the `res.sendStatus` in some of the paths, but not on others (when returning an object for example)

**Comment by swilliams-a3digital** [comment]
This was a breaking change and it just burned us.  We updated to address secure vulnerabilities and got this unexpected changed in behavior.  This change should have not been done in a minor patch and should have been documented as a breaking change.

**Pull request merged**
