### PR TITLE
BaseMiddleware support

### PR DESCRIPTION
**Pull request by remojansen**
## Description
An easy way to inject dependencies into middleware and access HttoContext from middleware

## Related Issue
inversify/InversifyJS/issues/673

## Motivation and Context
inversify/InversifyJS/issues/673
inversify/InversifyJS/issues/672

## How Has This Been Tested?
CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by remojansen** [comment]
Hi @codyjs @lholznagel @AltekkeE I'm having issues implementing this feature. I think I'm passing correctly middleware to the Router but it is never invoked. Maybe you guys can help me to spot what is the issue. Thanks!

**Comment by AltekkeE** [comment]
@remojansen It looks to me that the middleware is not the problem. I don't think that the route is even being hit. When I stripped away all the middleware and just tried to have super test hit the url i get a 404

```
        @controller("/")
        class TestController extends BaseHttpController {
            @httpGet("/testUrl", )
            public async getTest() {
                return "dog";
            }
        }

        const container = new Container();

        const server = new InversifyExpressServer(container);

        supertest(server.build())
            .get("/testUrl")
            .expect(200, `test@test.com`, (res: any) => {
                console.log(res.message)
                
                done();
            });
`

**Comment by AltekkeE** [comment]
Ok.. So i got "Hello from controller" Working

**Comment by remojansen** [comment]
Thanks a lot @AltekkeE it is working now 🎉

**Comment by remojansen** [comment]
I have solved the last issue 🎉 https://github.com/inversify/inversify-express-utils/blob/48602d6b4ce785f15b5824f80c160b2732f18da2/test/base_middleware.test.ts#L128-L131

**Pull request merged**
