### PR TITLE
Change JsonContent to return object rather than string

### PR DESCRIPTION
**Pull request by egmacke**
## Description

Resolves issue #378 by allowing objects to be sent without converting to strings.

## Related Issue

Issue #378 

## Motivation and Context

Solves the problem where some middleware expects Json objects rather than strings. Example: [`openapi-validator-middleware`](https://github.com/cdimascio/express-openapi-validator)

## How Has This Been Tested?

Updated unit tests.

Functionally tested by spinning up a server with various endpoints that return both Json and non-json responses.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

This change could possibly be a breaking change in downstream implementations where middleware has been configured to expect JsonResponse

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by PodaruDragos** [comment]
overall I am ok with this PR, but please find a better type for `object` like `Record<string, unknown>`

**Comment by egmacke** [comment]
@PodaruDragos thanks for the feedback. I've updated as suggested. I'd originally used `object` to avoid being overly opinionated, but I agree that using `Record` is a better solution.

**Comment by egmacke** [comment]
@PodaruDragos thanks.
@dcavanagh What's the release cycle for this repo? Just wondering when I'll be able to make use of this as part of a released version?

**Comment by Jameskmonger** [comment]
@egmacke sorry for the delay, I will publish this as `6.4.4` when I finish work today (#390)

**Comment by Jameskmonger** [comment]
Pleased to say this is now [published on npm in version 6.4.4](https://www.npmjs.com/package/inversify-express-utils/v/6.4.4) @egmacke

**Pull request merged**
