### PR TITLE
doc: add example of method sending only statusCode

### PR DESCRIPTION
**Pull request by aksharpatel47**
Looking at the examples in the Readme, my first impression was that response object was not available in the controller methods and that sending a status code other than 200 should be done in some other complex way. Adding this example to the Readme so that it helps others such as myself.

### CODE REVIEW

**Comment by lholznagel** [comment]
Great idea.
Maybe remove async / await for now and make it a promise? Or add the same example but with promise? Reason for that is that most people use promises.

**Comment by aksharpatel47** [comment]
@lholznagel True. Added another example that returns a promise.

**Comment by lholznagel** [comment]
:+1:
Just another idea: Add a catch to the promise, just to make it complete :), also Node can´t complain about uncaught promises.

**Comment by remojansen** [comment]
Thanks for this PR :+1: do you mind adding that last example mentioned by @lholznagel ? I will merge just after that :smile:

**Comment by aksharpatel47** [comment]
@remojansen Added the error handling in both the example methods.

**Comment by lholznagel** [comment]
LGTM
Thanks!

**Comment by lholznagel** [comment]
I am not sure if the async example would work without `sendStatus`, because the server technicly would never answer and the request runs in the timeout after some time.

**Comment by aksharpatel47** [comment]
@lholznagel Are you talking about the error handling part of async example?

**Comment by lholznagel** [comment]
Yes.

**Comment by aksharpatel47** [comment]
I deliberately didn't add anything in the error handling part so that people can handle error the way they usually do. If you think its important to add sendStatus statement there let me know, I'll add it.

**Comment by lholznagel** [comment]
I would say yes. When I start using inversify-express I would set up a small project and copy and paste the example and then start playing with it.

@remojansen what do you say?

**Comment by lholznagel** [comment]
Thanks!

LGTM :+1:

**Comment by remojansen** [comment]
@aksharpatel47 thanks a lot for your work :+1: and congrats for your first contribution to InversifyJS :1st_place_medal: 

@lholznagel thanks for the review :wink:

**Pull request merged**
