### PR TITLE
Upgraded dependencies and removed `I` prefix from interfaces.

### PR DESCRIPTION
**Pull request by remojansen**
## Description
Upgraded dependencies and removed `I` prefix from interfaces.

## Related Issue
#256

## Motivation and Context
#256

## How Has This Been Tested?
Build script

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] My change requires a change to the type definitions.
- [ ] I have updated the type definitions accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by codyjs** [comment]
Just curious, why remove the I prefix from interfaces? Was this a style change that happened in the main Inversify codebase as well?

**Comment by remojansen** [comment]
Yes, It was recommended by an user. He suggested it based on a [recommendation from the TS team](http://www.typescriptlang.org/docs/handbook/writing-declaration-files.html#naming-conventions):

> In general, you shouldn’t prefix interfaces with I (e.g. IColor). Because the concept of an interface in TypeScript is much more broad than in C# or Java, the IFoo naming convention is not broadly useful.

I have removed the `I` prefix from the interfaces in all our projects based in that.

**Comment by codyjs** [comment]
Great, thanks for the explanation!

**Comment by remojansen** [comment]
No worries there will be a release (beta.1) this evening I just need to update the .d.ts first :smile: We are going to change the way we [manage examples](https://github.com/inversify/InversifyJS/issues/265) and a new user has contributed already to [inversify-express-example](https://github.com/inversify/inversify-express-example). Would be good if you could take a look to see if the example is correct.

**Pull request merged**
